name: tpcdi
channels:
  - defaults
dependencies:
  - abseil-cpp=20211102.0=hc377ac9_0
  - arrow-cpp=10.0.1=py38h0fd5f32_0
  - asn1crypto=1.5.1=py38hca03da5_0
  - aws-c-common=0.6.8=h80987f9_1
  - aws-c-event-stream=0.1.6=h313beb8_6
  - aws-checksums=0.1.11=h80987f9_2
  - aws-sdk-cpp=1.8.185=h4a942e0_0
  - blas=1.0=openblas
  - boost-cpp=1.73.0=h1a28f6b_12
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py38h1a28f6b_1002
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.0=h80987f9_0
  - ca-certificates=2023.05.30=hca03da5_0
  - certifi=2023.5.7=py38hca03da5_0
  - cffi=1.15.1=py38h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cryptography=39.0.1=py38h834c97f_0
  - filelock=3.9.0=py38hca03da5_0
  - gflags=2.2.2=hc377ac9_0
  - glog=0.5.0=hc377ac9_0
  - gmp=6.2.1=hc377ac9_3
  - grpc-cpp=1.46.1=h8e4afa7_1
  - icu=68.1=hc377ac9_0
  - idna=3.4=py38hca03da5_0
  - krb5=1.20.1=h8380606_1
  - libboost=1.73.0=h49e8a49_12
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcurl=8.1.1=h0f1d93c_1
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20221030=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=hf27765b_0
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h1a28f6b_2
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.21=h269037a_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libssh2=1.10.0=h449679c_2
  - libthrift=0.13.0=hd358383_6
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - ncurses=6.4=h313beb8_0
  - numpy=1.24.3=py38h1398885_0
  - numpy-base=1.24.3=py38h90707a3_0
  - openssl=1.1.1u=h1a28f6b_0
  - orc=1.7.4=hdca1487_1
  - oscrypto=1.2.1=pyhd3eb1b0_0
  - packaging=23.0=py38hca03da5_0
  - pip=23.1.2=py38hca03da5_0
  - pyarrow=10.0.1=py38h23c13bc_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pycryptodomex=3.15.0=py38h1a28f6b_0
  - pyjwt=2.4.0=py38hca03da5_0
  - pyopenssl=23.0.0=py38hca03da5_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.17=hc0d8a6c_0
  - pytz=2022.7=py38hca03da5_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.29.0=py38hca03da5_0
  - setuptools=67.8.0=py38hca03da5_0
  - snappy=1.1.9=hc377ac9_0
  - snowflake-connector-python=3.0.3=py38h78102c4_0
  - snowflake-snowpark-python=1.5.1=py38hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - typing-extensions=4.6.3=py38hca03da5_0
  - typing_extensions=4.6.3=py38hca03da5_0
  - urllib3=1.26.16=py38hca03da5_0
  - utf8proc=2.6.1=h1a28f6b_0
  - wheel=0.38.4=py38hca03da5_0
  - xz=5.4.2=h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - click==8.1.6
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - pygments==2.15.1
      - rich==13.4.2
      - typer==0.9.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/tpcdi
